name: Deploy to ECR

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

defaults:
  run:
    working-directory: backend

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Image
      run: |
        docker build -t temp:latest -f Dockerfile .

      # OBI ECR
    - name: Configure AWS OBI ECR credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0

      with:
        role-to-assume: arn:aws:iam::985539765147:role/gh_ecr_push_neuroagent

        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-1

    - name: Login to Amazon OBI ECR
      id: login-ecr-management-obi-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Tag and Push Image to Amazon OBI ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr-management-obi-ecr.outputs.registry }}
        ECR_REPOSITORY: neuroagent
        IMAGE_TAG: neuroagent-${{ github.ref_name }}
      run: |
        docker tag temp:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
